# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build Package

on:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2
          registry-url: https://registry.npmjs.org/
      - run: npx yarn install --frozen-lockfile
      - run: npm run build
      - run: npm run test
      - run: npm run cy:run
      - run: npm run generate-md-docs
      - name: ✔️ Cypress Tests Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report
        if: github.repository == 'ShellyDCMS/ts-stubber'
        with:
          name: Cypress Tests
          path: ${{ github.workspace }}/cypress/results/json/mochawesome.json
          reporter: mochawesome-json
      - name: ✅ Jest Test Results
        uses: dorny/test-reporter@v1
        if: github.repository == 'ShellyDCMS/ts-stubber'
        with:
          name: JEST Tests # Name of the check run which will be created
          path: test-report.xml # Path to test results
          reporter: java-junit # Format of test results
